PortProton v1.4

diff --git a/portproton b/portproton
--- a/portproton
+++ b/portproton
@@ -4,18 +4,33 @@
 ########################################################################
 unset PW_AUTOPLAY PW_SET_LANG PW_SILENT_INSTALL
 export portname="PortProton"
-export port_ver=1.3
+export port_ver=1.4
 ########################################################################
 cd "$(dirname "$(readlink -f "$0")")"
 script_path="$(pwd)"
 ########################################################################
+fatal () {
+	echo -e "\n${1}\n"
+	exit 1
+}
 
-if [ "$script_path" == "/app/bin" ] ; then
+########################################################################
+if [ "$(id -u)" == "0" ] ; then
+	$yad_gui --error --text "\nDo not run ${portname} from the superuser!" 2>/dev/null
+	fatal "Do not run the script from the superuser!"
+fi
+########################################################################
+unset PW_USE_NS
+yad_gui="yad --window-icon=portproton.svg --borders=10 --center --text-align=center"
+
+if [ "$script_path" == "/app/bin" ] && [ -f "${PP_CONFIG_FILE}" ] ; then
 	export PORT_WINE_PATH="${XDG_DATA_HOME}"
 	if [ -f "${PORT_WINE_PATH}/scripts/start.sh" ] ; then
 		echo "${port_ver}" > "${PORT_WINE_PATH}/tmp/${portname}_ver"
 		/usr/bin/env bash "${PORT_WINE_PATH}/scripts/start.sh" "$@"
 		exit 0
+	else
+		rm -f "${PP_CONFIG_FILE}"
 	fi
 fi
 if locale | grep "LANG=ru_RU.UTF-8" 2>/dev/null
@@ -30,17 +45,17 @@ export INSTALLING_PORT=1
 case $PW_SET_LANG in
 	"Russian")
 		progress_bar() {
-		zenity --progress --title="Установка..." --text="Настройка ${portname}" --pulsate --auto-close --auto-kill --width=450 2>/dev/null
+		$yad_gui --progress --title="Установка..." --text="Настройка ${portname}" --pulsate --auto-close --auto-kill --width=500
 		} ;;
 	"English")
 		progress_bar() {
-		zenity --progress --title="Install..." --text="Install ${portname}" --pulsate --auto-close --auto-kill --width=450 2>/dev/null
+		$yad_gui --progress --title="Install..." --text="Install ${portname}" --pulsate --auto-close --auto-kill --width=500
 		} ;;
 esac
 ########################################################################
 export PORT_WINE_PATH="${XDG_DATA_HOME}"
 if [ ! -d "${PORT_WINE_PATH}" ] ; then
-    mkdir -p "$PORT_WINE_PATH" || exit 1
+    mkdir -p "$PORT_WINE_PATH" || fatal "Cannot create a directory: $PORT_WINE_PATH"
 else
 	rm -fr "${PORT_WINE_PATH}/tmp"
 	rm -f "${PORT_WINE_PATH}/scripts/"* 2>/dev/null
@@ -55,36 +70,30 @@ esac
 ########################################################################
 export PORT_WINE_TMP_PATH="${PORT_WINE_PATH}/tmp"
 cd "${PORT_WINE_PATH}"
-try_download_scripts () {
-	echo "Try download scripts from gitlab.eterfund.ru..."
-	if ! wget -O "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz" -nd -c --read-timeout 300 \
-		--retry-connrefused --timeout 15 --tries 3 \
-		--user-agent="Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" \
-		"https://gitlab.eterfund.ru/Castro-Fidel/PortWINE/-/archive/master/PortWINE-master.tar.gz"
-	then
-		echo -e "Error.\nTry download scripts from github.com..."
-		wget -O "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz" -nd -c --read-timeout 300 \
-		--retry-connrefused --timeout 15 --tries 3 \
-		--user-agent="Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" \
-		"https://github.com/Castro-Fidel/PortWINE/archive/refs/heads/master.tar.gz"
-		[ "$?" != "0" ] && echo "Fatal error! Exiting." && exit 1
-	fi
-	echo "Try unpacking scripts..."
-	tar -xvzf "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz" -C "${PORT_WINE_TMP_PATH}"
-	if [ "$?" = "0" ] ; then
-		[ ! -d "${PORT_WINE_PATH}" ] && mkdir "${PORT_WINE_PATH}"
-		cp -fr "${PORT_WINE_TMP_PATH}/PortWINE-master/data_from_portwine/"* "${PORT_WINE_PATH}"
-		rm -f "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
-		rm -fr "${PORT_WINE_TMP_PATH}/PortWINE-master/"
-		export scripts_current_ver=$(cat "${PORT_WINE_PATH}/scripts/var" | grep SCRIPTS_NEXT_VERSION | awk -F "=" '{print $2}')
-		echo "${scripts_current_ver}" > "${PORT_WINE_TMP_PATH}/scripts_ver"
-	else
-		rm -f "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
-		[ "$?" != "0" ] && echo "Fatal error! Exiting." && exit 1
-	fi
-}
+echo -e "\nTry download scripts from gitlab.eterfund.ru..."
+if ! curl -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
+	-L "https://gitlab.eterfund.ru/Castro-Fidel/PortWINE/-/archive/master/PortWINE-master.tar.gz" \
+	-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
+then
+	echo -e "\nError.\nTry download scripts from github.com..."
+	curl -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
+	-L "https://github.com/Castro-Fidel/PortWINE/archive/refs/heads/master.tar.gz" \
+	-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
+	[ "$?" != "0" ] && fatal "Critical error during file download!"
+fi
+echo "Try unpacking scripts..."
+tar -xvzf "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz" -C "${PORT_WINE_TMP_PATH}"
+if [ "$?" = "0" ] ; then
+	[ ! -d "${PORT_WINE_PATH}/data/" ] && mkdir "${PORT_WINE_PATH}/data/"
+	cp -fr "${PORT_WINE_TMP_PATH}/PortWINE-master/data_from_portwine/"* "${PORT_WINE_PATH}/data/"
+	rm -f "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
+	rm -fr "${PORT_WINE_TMP_PATH}/PortWINE-master/"
+	export scripts_current_ver=$(cat "${PORT_WINE_PATH}/scripts/var" | grep SCRIPTS_NEXT_VERSION | awk -F "=" '{print $2}')
+	echo "${scripts_current_ver}" > "${PORT_WINE_TMP_PATH}/scripts_ver"
+else
+	rm -f "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
+	[ "$?" != "0" ] && fatal "Critical error during file unpacking!"
+fi
 ########################################################################
-try_download_scripts | progress_bar
 cd "${PORT_WINE_PATH}/scripts"
 /usr/bin/env bash "${PORT_WINE_PATH}/scripts/setup.sh" && exit 0
-################################ARCH_BIN################################
